export const post = {
  id: 123,
  title: "Software Engineer",
  location: {
    id: 123456,
    name: "New York, NY",
    office_id: null,
    job_post_custom_location_id: 303145,
    job_post_location_type: {
      id: 1,
      name: "Free Text",
    },
  },
  internal: true,
  external: false,
  active: true,
  live: true,
  first_published_at: "2023-04-03T18:06:18Z",
  job_id: 1234,
  content: "<p>We’re looking for the next big innovator.</p>",
  internal_content: "<p>Apply today!</p>",
  updated_at: "2024-11-21T15:39:24Z",
  created_at: "2023-04-01T17:56:19Z",
  demographic_question_set_id: 999,
  questions: [
    {
      required: true,
      private: false,
      label: "First Name",
      name: "first_name",
      type: "short_text",
      values: [],
      description: null,
    },
    {
      required: true,
      private: false,
      label: "Last Name",
      name: "last_name",
      type: "short_text",
      values: [],
      description: null,
    },
    {
      required: true,
      private: false,
      label: "Email",
      name: "email",
      type: "short_text",
      values: [],
      description: null,
    },
    {
      required: false,
      private: false,
      label: "Phone",
      name: "phone",
      type: "short_text",
      values: [],
      description: null,
    },
    {
      required: true,
      private: false,
      label: "Resume",
      name: "resume",
      type: "attachment",
      values: [],
      description: null,
    },
    {
      required: false,
      private: false,
      label: "Cover Letter",
      name: "cover_letter",
      type: "attachment",
      values: [],
      description: null,
    },
    {
      required: false,
      private: false,
      label: "Have you ever worked for our organization before?",
      name: "question_234567",
      type: "boolean",
      values: [
        {
          value: 0,
          label: "No",
        },
        {
          value: 1,
          label: "Yes",
        },
      ],
      description: "<p>Please select Yes or No.</p>",
    },
    {
      required: false,
      private: true,
      label: "Have you applied to this job before?",
      type: "multi_select",
      name: "question_345678[]",
      values: [
        {
          value: 862,
          label: "Yes",
        },
        {
          value: 863,
          label: "No",
        },
        {
          value: 864,
          label: "Maybe",
        },
      ],
      description: null,
    },
    {
      required: true,
      private: false,
      label: "LinkedIn Profile",
      name: "question_45678",
      type: "short_text",
      values: [],
      description: "<p>Please enter the URL for your LinkedIn profile.</p>",
    },
    {
      required: true,
      private: false,
      label: "How did you hear about this job?",
      name: "question_56789",
      type: "short_text",
      values: [],
      description: null,
    },
  ],
};
